{
 "title": "Quilibrium Network",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "Peer", "query": { "query": "label_values(peerId)" } },
   { "name": "Address", "query": { "query": "label_values(peerId)" } }
  ]
 },
 "panels": [
  { "title": "Peer Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Discovered Peers",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(Quilibrium_PeerInfo_maxFrame{}) + 1",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PeerInfo_maxFrame",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 20, "x": 3, "y": 1 },
   "targets": [
    {
     "expr": "Quilibrium_PeerInfo_maxFrame{peerId=~\"$Peer\", multiaddrs=~\"$Address\"}",
     "legendFormat": "{{peerId}} ({{multiaddrs}})"
    }
   ]
  },
  {
   "title": "Network Peers",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(Quilibrium_NetworkInfo_peerScore{}) +1",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Version",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(Quilibrium_LatestFrame_truncatedClockFrames_frameNumber)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Version & Difficulty",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 20, "x": 3, "y": 12 },
   "targets": [
    {
     "expr": "Quilibrium_LatestFrame_truncatedClockFrames_frameNumber",
     "legendFormat": "__auto"
    },
    {
     "expr": "Quilibrium_LatestFrame_truncatedClockFrames_difficulty",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Difficulty",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "Quilibrium_LatestFrame_truncatedClockFrames_difficulty",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Quil Supply",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "Quilibrium_TokenInfo_confirmedTokenSupply / 8000000000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Confirmed Quil Supply",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 20, "x": 3, "y": 22 },
   "targets": [
    {
     "expr": "Quilibrium_TokenInfo_confirmedTokenSupply / 8000000000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "UC Quil Supply",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "Quilibrium_TokenInfo_unconfirmedTokenSupply / 8000000000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Unconfirmed Quil Supply",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 20, "x": 3, "y": 30 },
   "targets": [
    {
     "expr": "Quilibrium_TokenInfo_unconfirmedTokenSupply / 8000000000",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Other Peer Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "NetworkInfo_peerScore",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 23, "x": 0, "y": 37 },
   "targets": [
    {
     "expr": "Quilibrium_NetworkInfo_peerScore{peerId=~\"$Peer\", multiaddrs=~\"$Address\"}",
     "legendFormat": "{{peerId}} ({{multiaddrs}})"
    }
   ]
  },
  {
   "title": "PeerInfo_uncooperativePeerInfo_maxFrame",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 23, "x": 0, "y": 47 },
   "targets": [
    {
     "expr": "Quilibrium_PeerInfo_uncooperativePeerInfo_maxFrame{}",
     "legendFormat": "{{peerId}} ({{multiaddrs}})"
    }
   ]
  }
 ]
}